In [ ]:
import numpy as np
import pandas as pd
 
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [ ]:
from google.colab import drive
import csv
drive.mount('/content/gdrive')
file = open("gdrive/My Drive/Colab Notebooks/dataset-loc.csv")
names = ['Latitude', 'Longtitude', 'Kota']

dataset = pd.read_csv(file, names=names)

dat = dataset.astype('int')

print(dat)

Mounted at /content/gdrive
    Latitude  Longtitude  Kota
0         11          26     1
1         15          29     1
2         19          28     1
3         18          30     1
4         16          26     1
5         23          25     2
6         25          22     2
7         21          24     2
8         23          25     2
9         29          24     2
10        19          25     0


In [ ]:
X = dat.drop(["Kota"], axis=1)
X.head()

Latitude  Longtitude
0        11          26
1        15          29
2        19          28
3        18          30
4        16          26

In [ ]:
y = dat["Kota"]
print(y)

0     1
1     1
2     1
3     1
4     1
5     2
6     2
7     2
8     2
9     2
10    0
Name: Kota, dtype: int64


In [ ]:
#split
X = dat.iloc[:, :-1].values
y = dat.iloc[:, 2].values

#training data:test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2) 

In [ ]:
#scaling
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
#predict
y_pred = knn.predict(X_test)
y_pred

array([0, 2, 1])

In [ ]:
#predict result
print(confusion_matrix(y_test, y_pred))

[[0 0 0]
 [1 1 0]
 [0 0 1]]


In [ ]:
#accuracy predict result
print(classification_report(y_test, y_pred))
print("K=1 test")
print("K=3 test\n")

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.50      0.67         2
           2       1.00      1.00      1.00         1

    accuracy                           0.67         3
   macro avg       0.67      0.50      0.56         3
weighted avg       1.00      0.67      0.78         3

K=1 test
K=3 test



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print(y_test)

[1 2 1]
